version: '3'
services:
  react-app:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /user/app/node_modules
      - .:/user/app
    ports:
      - "4000:3000"
